# Generated by Django 5.0 on 2024-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryWeatherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('city_id', models.CharField(max_length=20)),
                ('city_province', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=10)),
                ('high_temp', models.IntegerField()),
                ('low_temp', models.IntegerField()),
                ('w_direction', models.CharField(max_length=10)),
                ('w_level', models.CharField(max_length=10)),
                ('aqi', models.IntegerField()),
                ('aqi_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('city_id', models.CharField(max_length=20)),
                ('city_province', models.CharField(max_length=20)),
                ('temp', models.FloatField()),
                ('d_temp', models.FloatField()),
                ('n_temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('w_direction', models.CharField(max_length=10)),
                ('w_level', models.CharField(max_length=10)),
                ('w_speed', models.IntegerField()),
                ('rain', models.IntegerField()),
                ('rain24h', models.IntegerField()),
                ('aqi', models.IntegerField()),
                ('description', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
            ],
        ),
    ]
