# Generated by Django 5.0 on 2024-01-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryWeatherItem',
            new_name='HistoryData',
        ),
    ]
