# Generated by Django 5.0 on 2024-01-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_realdata_content_alter_realdata_rain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='aqi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='aqi_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='city_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
