# Generated by Django 5.0 on 2024-01-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_historydata_aqi_alter_historydata_aqi_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='city_id',
            field=models.CharField(max_length=20),
        ),
    ]
