# Generated by Django 5.0 on 2024-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_realdata_d_temp_alter_realdata_n_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realdata',
            name='w_level',
            field=models.IntegerField(),
        ),
    ]
